### ISSUE TITLE
Уведомление о регистрации заявки

### ISSUE THREAD

**Issue by iljaiwjew** [paralect/startup-summer#4]
Должно ли приходить письмо с подтверждением регистрации? Мне ничего не пришло, не знаю зарегистрировался я или нет.

**Comment by anorsich** [comment]
@ilyaivjev Вы зарегистрированы, не волнуйтесь. Подтверждение, к сожалению, не приходит.

**Comment by anton-paskanny** [comment]
Такой же вопрос: можно узнать, зарегистрировался ли я? Спасибо)

**Comment by anorsich** [comment]
@anton-paskannyi Да, вы зарегистрированы! Ждите приглашения на собеседование ;)

**Comment by susierock17** [comment]
Здравствуйте, аналогичный вопрос: можно ли узнать, зарегистрирована ли я? Заранее спасибо:)

**Comment by anorsich** [comment]
@susierock17 Да, вы зарегистрированы! Определенно надо добавить уведомление :)

**Comment by t2n3qqq** [comment]
Здравствуйте, не смог заполнить и отправить форму регистрации с Вашего сайта (он был  недоступен), однако откликнулся на вакансию на tut.by, указав в сопроводительном письме ссылку на выполненное тестовое задание. Могу ли я узнать, получили ли Вы мой отклик и был ли я зарегистрирован? 
Заранее спасибо)

**Comment by norkfy** [comment]
Добрый день, чекните и мою тогда. Подписывался как Горбунов Александр.

**Comment by anorsich** [comment]
@lyxd Вы тоже зарегистрированы!

**Comment by ilyaivjev** [comment]
Мне не пришёл ответ о результатах собеседования. Его ещё стоит ждать?)
