### ISSUE TITLE
Deadline

### ISSUE THREAD

**Issue by Drapegnik** [paralect/startup-summer#6]
Здравствуйте! Скажите, пожалуйста, до какой даты можно регистрироваться на Startup Summer, то есть когда регистрация будет закрыта?

**Comment by anorsich** [comment]
Добрый день, Иван! @Drapegnik 

У нас нету четкой даты закрытия регистация. В прошлом году мы закрыли регистрацию приблизительно за неделю до начала курсов. Основная причина - это большое количество желающих, которых мы бы просто не успели прособеседовать до начала курсов. 

Я бы рекомендовал постораться подать заявку до 1 июня, крайний срок - 15 июня (с вероятностью 90% регистрация будет открыта). В крайних случаях, при большом желании, можно писать нарямую даже после закрытия регистрации на andrew at paralect dot com. 

Андрей.

**Comment by anorsich** [comment]
Update: Регистрация будет открыта до 27 июня, еще есть все шансы записаться и попасть на курсы.
